export {
  DEFAULT_KODI_HTTP_PATH,
  DEFAULT_KODI_HTTP_PORT,
  DEFAULT_KODI_TIMEOUT_MS,
  buildBasicAuthHeader,
  buildKodiJsonRpcHttpUrl,
  buildKodiRequestHeaders,
  describeKodiEndpoint,
  normalizeKodiHttpHost,
  type KodiEndpointDescription,
  type KodiHttpHost,
  type NormalizedKodiHttpHost
} from './host';

export {
  KodiHttpClientError,
  createKodiJsonRpcHttpClient,
  getKodiHttpClientErrorMessage,
  isKodiHttpClientError,
  type JsonRpcError,
  type JsonRpcFailure,
  type JsonRpcId,
  type JsonRpcParams,
  type JsonRpcRequest,
  type JsonRpcSuccess,
  type KodiHttpCallOptions,
  type KodiHttpClientErrorCode,
  type KodiHttpClientErrorDetails,
  type KodiHttpClientOptions,
  type KodiJsonRpcHttpClient
} from './jsonRpc';

export {
  getActivePlayers,
  getApplicationProperties,
  getAudioLibraryAlbums,
  getAudioLibraryArtists,
  getAudioLibrarySongs,
  getFileSources,
  getJsonRpcVersion,
  getPlayerProperties,
  getSystemProperties,
  getVideoLibraryEpisodes,
  getVideoLibraryMovies,
  getVideoLibraryTvShows,
  pingKodi,
  prepareFileDownload,
  testKodiHttpConnection,
  type ActivePlayer,
  type ApplicationPropertiesResult,
  type ApplicationPropertyName,
  type AudioLibraryAlbum,
  type AudioLibraryAlbumPropertyName,
  type AudioLibraryAlbumsParams,
  type AudioLibraryAlbumsResult,
  type AudioLibraryArtist,
  type AudioLibraryArtistPropertyName,
  type AudioLibraryArtistsParams,
  type AudioLibraryArtistsResult,
  type AudioLibrarySong,
  type AudioLibrarySongPropertyName,
  type AudioLibrarySongsParams,
  type AudioLibrarySongsResult,
  type FileMediaType,
  type FileSource,
  type FileSourcesResult,
  type JsonRpcVersionResult,
  type KodiHttpConnectionTestResult,
  type KodiLimits,
  type KodiListParams,
  type KodiPropertiesRequest,
  type KodiVersion,
  type LibraryItem,
  type PlayerPropertiesParams,
  type PlayerPropertiesResult,
  type PlayerPropertyName,
  type PlayerType,
  type PrepareFileDownloadResult,
  type SystemPropertiesResult,
  type SystemPropertyName,
  type VideoLibraryEpisode,
  type VideoLibraryEpisodePropertyName,
  type VideoLibraryEpisodesParams,
  type VideoLibraryEpisodesResult,
  type VideoLibraryMovie,
  type VideoLibraryMoviePropertyName,
  type VideoLibraryMoviesParams,
  type VideoLibraryMoviesResult,
  type VideoLibraryTvShow,
  type VideoLibraryTvShowPropertyName,
  type VideoLibraryTvShowsParams,
  type VideoLibraryTvShowsResult
} from './methods';
