export {
  DEFAULT_KODI_HTTP_PATH,
  DEFAULT_KODI_HTTP_PORT,
  DEFAULT_KODI_TIMEOUT_MS,
  DEFAULT_KODI_WEBSOCKET_PATH,
  DEFAULT_KODI_WEBSOCKET_PORT,
  buildBasicAuthHeader,
  buildKodiJsonRpcHttpUrl,
  buildKodiJsonRpcWebSocketUrl,
  buildKodiRequestHeaders,
  describeKodiEndpoint,
  describeKodiWebSocketEndpoint,
  normalizeKodiHttpHost,
  normalizeKodiWebSocketHost,
  type KodiEndpointDescription,
  type KodiHttpHost,
  type KodiWebSocketEndpointDescription,
  type KodiWebSocketHost,
  type NormalizedKodiHttpHost,
  type NormalizedKodiWebSocketHost
} from './host';

export {
  KodiHttpClientError,
  createKodiJsonRpcHttpClient,
  getKodiHttpClientErrorMessage,
  isKodiHttpClientError,
  type JsonRpcError,
  type JsonRpcFailure,
  type JsonRpcId,
  type JsonRpcParams,
  type JsonRpcRequest,
  type JsonRpcSuccess,
  type KodiHttpCallOptions,
  type KodiHttpClientErrorCode,
  type KodiHttpClientErrorDetails,
  type KodiHttpClientOptions,
  type KodiJsonRpcHttpClient
} from './jsonRpc';

export {
  parseKodiNotificationMessage,
  type JsonRpcNotificationEnvelope,
  type JsonRpcRequestEnvelope,
  type JsonRpcResponseEnvelope,
  type KodiKnownNotificationMethod,
  type KodiNotification,
  type KodiNotificationParams,
  type KodiNotificationParseResult,
  type KnownKodiNotification,
  type MalformedKodiNotification,
  type MalformedKodiNotificationCode,
  type MalformedKodiNotificationDetails,
  type UnknownKodiNotification
} from './notifications';

export {
  createKodiJsonRpcWebSocketClient,
  type KodiWebSocketClient,
  type KodiWebSocketClientError,
  type KodiWebSocketClientErrorCode,
  type KodiWebSocketClientEvent,
  type KodiWebSocketClientListener,
  type KodiWebSocketClientOptions,
  type KodiWebSocketImplementation,
  type KodiWebSocketLike,
  type KodiWebSocketSendFailure,
  type KodiWebSocketSendResult,
  type KodiWebSocketSendSuccess,
  type KodiWebSocketUnsubscribe
} from './webSocket';

export {
  addEpisodePlaylistItem,
  addFilePlaylistItem,
  addMoviePlaylistItem,
  addMusicVideoPlaylistItem,
  addMusicPlaylistItem,
  addPlaylistFileItem,
  addPlaylistItem,
  cleanAudioLibrary,
  cleanVideoLibrary,
  clearPlaylist,
  executeAddon,
  executeInputAction,
  getAddonDetails,
  getAddons,
  getActivePlayers,
  getApplicationProperties,
  getAudioLibraryAlbums,
  getAudioLibraryArtists,
  getAudioLibraryGenres,
  getAudioLibrarySongs,
  getFileDirectory,
  getFileDetails,
  getFileSources,
  getJsonRpcIntrospection,
  getJsonRpcVersion,
  getPlayerItem,
  getPlayerProperties,
  getPlaylistItems,
  getPvrBroadcasts,
  getPvrChannelDetails,
  getPvrChannels,
  getPvrRecordingDetails,
  getPvrRecordings,
  recordPvrChannel,
  togglePvrTimer,
  addPvrTimer,
  deletePvrTimer,
  getSettings,
  getSettingsCategories,
  getSettingsSections,
  getSystemProperties,
  getVideoLibraryEpisodes,
  getVideoLibraryMusicVideoDetails,
  getVideoLibraryMusicVideos,
  getVideoLibraryMovieDetails,
  getVideoLibraryMovies,
  getVideoLibraryTvShows,
  getVideoLibraryTvShowDetails,
  getVideoLibrarySeasons,
  getVideoLibrarySeasonDetails,
  getVideoLibraryEpisodeDetails,
  getVideoLibraryAvailableArt,
  getVideoLibraryAvailableArtTypes,
  insertPlaylistItem,
  refreshVideoLibraryMovie,
  refreshVideoLibraryTvShow,
  refreshVideoLibraryEpisode,
  goToPlayerItem,
  openPlayer,
  openPlayerEpisodeItem,
  openPlayerFile,
  openPlayerItem,
  openPlayerMovieItem,
  openPlayerPlaylistFile,
  pingKodi,
  playPausePlayer,
  prepareFileDownload,
  REMOTE_INPUT_ACTIONS,
  REMOTE_INPUT_COMMANDS,
  sendInputCommand,
  sendInputText,
  removePlaylistItem,
  seekPlayer,
  scanAudioLibrary,
  scanVideoLibrary,
  setAddonEnabled,
  setApplicationMute,
  setApplicationVolume,
  setAlbumDetails,
  setArtistDetails,
  setEpisodeDetails,
  setMovieDetails,
  setMusicVideoDetails,
  setSeasonDetails,
  setTvShowDetails,
  setPlayerAudioStream,
  setPlayerPartyMode,
  setPlayerRepeat,
  setPlayerShuffle,
  setPlayerSubtitle,
  setSettingValue,
  setSongDetails,
  stopPlayer,
  swapPlaylistItems,
  testKodiHttpConnection,
  type ActivePlayer,
  type AddonDetail,
  type AddonEnabledFilter,
  type AddonInstalledFilter,
  type AddonPropertyName,
  type AddonSetEnabledValue,
  type AddonSummary,
  type AddonsExecuteAddonParams,
  type AddonsExecuteAddonResult,
  type AddonsGetAddonDetailsParams,
  type AddonsGetAddonDetailsResult,
  type AddonsGetAddonsParams,
  type AddonsGetAddonsResult,
  type AddonsSetAddonEnabledParams,
  type AddonsSetAddonEnabledResult,
  type ApplicationMuteValue,
  type ApplicationPropertiesResult,
  type ApplicationPropertyName,
  type ApplicationSetMuteParams,
  type ApplicationSetVolumeParams,
  type ApplicationVolumeValue,
  type AudioLibraryAlbum,
  type AudioLibraryAlbumPropertyName,
  type AudioLibraryAlbumsParams,
  type AudioLibraryAlbumsResult,
  type AudioLibraryArtist,
  type AudioLibraryArtistPropertyName,
  type AudioLibraryArtistsParams,
  type AudioLibraryArtistsResult,
  type AudioLibraryGenre,
  type AudioLibraryGenrePropertyName,
  type AudioLibraryGenresParams,
  type AudioLibraryGenresResult,
  type AudioLibraryCleanParams,
  type AudioLibraryScanParams,
  type AudioLibrarySetAlbumDetailsParams,
  type AudioLibrarySetArtistDetailsParams,
  type AudioLibrarySetSongDetailsParams,
  type AudioLibrarySong,
  type AudioLibrarySongPropertyName,
  type AudioLibrarySongsParams,
  type AudioLibrarySongsResult,
  type FileDirectoryEntry,
  type FileDirectoryParams,
  type FileDirectoryPropertyName,
  type FileDirectoryResult,
  type FileDetailsParams,
  type FileDetailsResult,
  type FileMediaType,
  type FileSource,
  type FileSourcesResult,
  type JsonRpcIntrospectionParams,
  type JsonRpcIntrospectionResult,
  type JsonRpcVersionResult,
  type KodiEpisodeLibraryItem,
  type KodiFileItem,
  type KodiHttpConnectionTestResult,
  type KodiLibraryWriteResult,
  type KodiLimits,
  type KodiListParams,
  type KodiMovieLibraryItem,
  type KodiMusicVideoLibraryItem,
  type KodiMusicLibraryItem,
  type KodiPlaylistFileItem,
  type KodiPvrChannelItem,
  type KodiPropertiesRequest,
  type KodiSettingsCategory,
  type KodiSettingsSection,
  type KodiSettingsSetting,
  type KodiTime,
  type KodiVersion,
  type LibraryItem,
  type PlayerAudioStream,
  type PlayerAudioStreamValue,
  type PlayerCommandResult,
  type PlayerGoToParams,
  type PlayerGoToTarget,
  type PlayerItem,
  type PlayerItemParams,
  type PlayerItemPropertyName,
  type PlayerItemResult,
  type PlayerOpenItem,
  type PlayerOpenMovieParams,
  type PlayerOpenParams,
  type PlayerPartyModeValue,
  type PlayerPlayPauseParams,
  type PlayerPlayPauseResult,
  type PlayerPropertiesParams,
  type PlayerPropertiesResult,
  type PlayerPropertyName,
  type PlayerRepeatValue,
  type RemoteInputAction,
  type RemoteInputCommand,
  type PlayerSeekParams,
  type PlayerSeekResult,
  type PlayerSeekStep,
  type PlayerSeekValue,
  type PlayerSetAudioStreamParams,
  type PlayerSetPartyModeParams,
  type PlayerSetRepeatParams,
  type PlayerSetShuffleParams,
  type PlayerSetSubtitleParams,
  type PlayerShuffleValue,
  type PlayerStopParams,
  type PlayerSubtitleStream,
  type PlayerSubtitleValue,
  type PlayerType,
  type PlayerVideoStream,
  type PlaylistAddParams,
  type PlaylistAddMovieParams,
  type PlaylistAddEpisodeParams,
  type PlaylistAddMusicVideoParams,
  type PlaylistInsertItem,
  type PlaylistInsertParams,
  type PlayerOpenEpisodeParams,
  type PlayerOpenFileParams,
  type PlayerOpenPlaylistFileParams,
  type FilePlaylistAddParams,
  type PlaylistFileAddParams,
  type PlaylistClearParams,
  type PlaylistGetItemsParams,
  type PlaylistItem,
  type PlaylistItemPropertyName,
  type PlaylistItemsResult,
  type PlaylistRemoveParams,
  type PlaylistSwapParams,
  type PrepareFileDownloadResult,
  type PvrBroadcast,
  type PvrBroadcastPropertyName,
  type PvrChannel,
  type PvrChannelPropertyName,
  type PvrDeleteTimerParams,
  type PvrGetBroadcastsParams,
  type PvrGetBroadcastsResult,
  type PvrGetChannelDetailsParams,
  type PvrGetChannelDetailsResult,
  type PvrGetChannelsParams,
  type PvrGetChannelsResult,
  type PvrGetRecordingDetailsParams,
  type PvrGetRecordingDetailsResult,
  type PvrGetRecordingsParams,
  type PvrGetRecordingsResult,
  type PvrRecordParams,
  type PvrRecording,
  type PvrRecordingPropertyName,
  type PvrTimerBroadcastParams,
  type SettingsGetCategoriesParams,
  type SettingsGetCategoriesResult,
  type SettingsGetSectionsParams,
  type SettingsGetSectionsResult,
  type SettingsGetSettingsParams,
  type SettingsGetSettingsResult,
  type SettingsLevel,
  type SettingsSetSettingValueParams,
  type SettingsSetSettingValueResult,
  type SettingsSettingValue,
  type SystemPropertiesResult,
  type SystemPropertyName,
  type VideoLibraryEpisode,
  type VideoLibraryEpisodeDetailsParams,
  type VideoLibraryEpisodeDetailsResult,
  type VideoLibraryEpisodePropertyName,
  type VideoLibraryEpisodesParams,
  type VideoLibraryEpisodesResult,
  type VideoLibraryMusicVideo,
  type VideoLibraryMusicVideoDetailsParams,
  type VideoLibraryMusicVideoDetailsResult,
  type VideoLibraryMusicVideoPropertyName,
  type VideoLibraryMusicVideosParams,
  type VideoLibraryMusicVideosResult,
  type VideoLibraryCleanParams,
  type VideoLibraryAvailableArtMedia,
  type VideoLibraryAvailableArtParams,
  type VideoLibraryAvailableArtResult,
  type VideoLibraryAvailableArtTypesParams,
  type VideoLibraryAvailableArtTypesResult,
  type VideoLibraryMovie,
  type VideoLibraryMovieDetailsParams,
  type VideoLibraryMovieDetailsResult,
  type VideoLibraryMoviePropertyName,
  type VideoLibraryMoviesParams,
  type VideoLibraryMoviesResult,
  type VideoLibrarySetEpisodeDetailsParams,
  type VideoLibrarySetMovieDetailsParams,
  type VideoLibrarySetMusicVideoDetailsParams,
  type VideoLibrarySetSeasonDetailsParams,
  type VideoLibrarySetTvShowDetailsParams,
  type VideoLibrarySeason,
  type VideoLibrarySeasonDetailsParams,
  type VideoLibrarySeasonDetailsResult,
  type VideoLibrarySeasonPropertyName,
  type VideoLibrarySeasonsParams,
  type VideoLibrarySeasonsResult,
  type VideoLibraryRefreshEpisodeParams,
  type VideoLibraryRefreshMovieParams,
  type VideoLibraryRefreshTvShowParams,
  type VideoLibraryScanParams,
  type VideoLibraryTvShow,
  type VideoLibraryTvShowDetailsParams,
  type VideoLibraryTvShowDetailsResult,
  type VideoLibraryTvShowPropertyName,
  type VideoLibraryTvShowsParams,
  type VideoLibraryTvShowsResult,
  type VideoResumePosition
} from './methods';
