export {
  DEFAULT_KODI_HTTP_PATH,
  DEFAULT_KODI_HTTP_PORT,
  DEFAULT_KODI_TIMEOUT_MS,
  DEFAULT_KODI_WEBSOCKET_PATH,
  DEFAULT_KODI_WEBSOCKET_PORT,
  buildBasicAuthHeader,
  buildKodiJsonRpcHttpUrl,
  buildKodiJsonRpcWebSocketUrl,
  buildKodiRequestHeaders,
  describeKodiEndpoint,
  describeKodiWebSocketEndpoint,
  normalizeKodiHttpHost,
  normalizeKodiWebSocketHost,
  type KodiEndpointDescription,
  type KodiHttpHost,
  type KodiWebSocketEndpointDescription,
  type KodiWebSocketHost,
  type NormalizedKodiHttpHost,
  type NormalizedKodiWebSocketHost
} from './host';

export {
  KodiHttpClientError,
  createKodiJsonRpcHttpClient,
  getKodiHttpClientErrorMessage,
  isKodiHttpClientError,
  type JsonRpcError,
  type JsonRpcFailure,
  type JsonRpcId,
  type JsonRpcParams,
  type JsonRpcRequest,
  type JsonRpcSuccess,
  type KodiHttpCallOptions,
  type KodiHttpClientErrorCode,
  type KodiHttpClientErrorDetails,
  type KodiHttpClientOptions,
  type KodiJsonRpcHttpClient
} from './jsonRpc';

export {
  parseKodiNotificationMessage,
  type JsonRpcNotificationEnvelope,
  type JsonRpcRequestEnvelope,
  type JsonRpcResponseEnvelope,
  type KodiKnownNotificationMethod,
  type KodiNotification,
  type KodiNotificationParams,
  type KodiNotificationParseResult,
  type KnownKodiNotification,
  type MalformedKodiNotification,
  type MalformedKodiNotificationCode,
  type MalformedKodiNotificationDetails,
  type UnknownKodiNotification
} from './notifications';

export {
  createKodiJsonRpcWebSocketClient,
  type KodiWebSocketClient,
  type KodiWebSocketClientError,
  type KodiWebSocketClientErrorCode,
  type KodiWebSocketClientEvent,
  type KodiWebSocketClientListener,
  type KodiWebSocketClientOptions,
  type KodiWebSocketImplementation,
  type KodiWebSocketLike,
  type KodiWebSocketSendFailure,
  type KodiWebSocketSendResult,
  type KodiWebSocketSendSuccess,
  type KodiWebSocketUnsubscribe
} from './webSocket';

export {
  addFilePlaylistItem,
  addMusicPlaylistItem,
  addPlaylistFileItem,
  addPlaylistItem,
  clearPlaylist,
  getActivePlayers,
  getApplicationProperties,
  getAudioLibraryAlbums,
  getAudioLibraryArtists,
  getAudioLibraryGenres,
  getAudioLibrarySongs,
  getFileDirectory,
  getFileSources,
  getJsonRpcVersion,
  getPlayerItem,
  getPlayerProperties,
  getPlaylistItems,
  getSystemProperties,
  getVideoLibraryEpisodes,
  getVideoLibraryMovies,
  getVideoLibraryTvShows,
  goToPlayerItem,
  openPlayer,
  openPlayerFile,
  openPlayerItem,
  openPlayerPlaylistFile,
  pingKodi,
  playPausePlayer,
  prepareFileDownload,
  removePlaylistItem,
  seekPlayer,
  setApplicationMute,
  setApplicationVolume,
  setEpisodeDetails,
  setMovieDetails,
  setPlayerAudioStream,
  setPlayerRepeat,
  setPlayerShuffle,
  setPlayerSubtitle,
  setSongDetails,
  stopPlayer,
  swapPlaylistItems,
  testKodiHttpConnection,
  type ActivePlayer,
  type ApplicationMuteValue,
  type ApplicationPropertiesResult,
  type ApplicationPropertyName,
  type ApplicationSetMuteParams,
  type ApplicationSetVolumeParams,
  type ApplicationVolumeValue,
  type AudioLibraryAlbum,
  type AudioLibraryAlbumPropertyName,
  type AudioLibraryAlbumsParams,
  type AudioLibraryAlbumsResult,
  type AudioLibraryArtist,
  type AudioLibraryArtistPropertyName,
  type AudioLibraryArtistsParams,
  type AudioLibraryArtistsResult,
  type AudioLibraryGenre,
  type AudioLibraryGenrePropertyName,
  type AudioLibraryGenresParams,
  type AudioLibraryGenresResult,
  type AudioLibrarySetSongDetailsParams,
  type AudioLibrarySong,
  type AudioLibrarySongPropertyName,
  type AudioLibrarySongsParams,
  type AudioLibrarySongsResult,
  type FileDirectoryEntry,
  type FileDirectoryParams,
  type FileDirectoryPropertyName,
  type FileDirectoryResult,
  type FileMediaType,
  type FileSource,
  type FileSourcesResult,
  type JsonRpcVersionResult,
  type KodiFileItem,
  type KodiHttpConnectionTestResult,
  type KodiLibraryWriteResult,
  type KodiLimits,
  type KodiListParams,
  type KodiMusicLibraryItem,
  type KodiPlaylistFileItem,
  type KodiPropertiesRequest,
  type KodiTime,
  type KodiVersion,
  type LibraryItem,
  type PlayerAudioStream,
  type PlayerAudioStreamValue,
  type PlayerCommandResult,
  type PlayerGoToParams,
  type PlayerGoToTarget,
  type PlayerItem,
  type PlayerItemParams,
  type PlayerItemPropertyName,
  type PlayerItemResult,
  type PlayerOpenItem,
  type PlayerOpenParams,
  type PlayerPlayPauseParams,
  type PlayerPlayPauseResult,
  type PlayerPropertiesParams,
  type PlayerPropertiesResult,
  type PlayerPropertyName,
  type PlayerRepeatValue,
  type PlayerSeekParams,
  type PlayerSeekResult,
  type PlayerSeekStep,
  type PlayerSeekValue,
  type PlayerSetAudioStreamParams,
  type PlayerSetRepeatParams,
  type PlayerSetShuffleParams,
  type PlayerSetSubtitleParams,
  type PlayerShuffleValue,
  type PlayerStopParams,
  type PlayerSubtitleStream,
  type PlayerSubtitleValue,
  type PlayerType,
  type PlayerVideoStream,
  type PlaylistAddParams,
  type PlayerOpenFileParams,
  type PlayerOpenPlaylistFileParams,
  type FilePlaylistAddParams,
  type PlaylistFileAddParams,
  type PlaylistClearParams,
  type PlaylistGetItemsParams,
  type PlaylistItem,
  type PlaylistItemPropertyName,
  type PlaylistItemsResult,
  type PlaylistRemoveParams,
  type PlaylistSwapParams,
  type PrepareFileDownloadResult,
  type SystemPropertiesResult,
  type SystemPropertyName,
  type VideoLibraryEpisode,
  type VideoLibraryEpisodePropertyName,
  type VideoLibraryEpisodesParams,
  type VideoLibraryEpisodesResult,
  type VideoLibraryMovie,
  type VideoLibraryMoviePropertyName,
  type VideoLibraryMoviesParams,
  type VideoLibraryMoviesResult,
  type VideoLibrarySetEpisodeDetailsParams,
  type VideoLibrarySetMovieDetailsParams,
  type VideoLibraryTvShow,
  type VideoLibraryTvShowPropertyName,
  type VideoLibraryTvShowsParams,
  type VideoLibraryTvShowsResult,
  type VideoResumePosition
} from './methods';
